# Generated by Django 5.0.6 on 2024-06-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('articles', models.CharField(max_length=255)),
                ('videos', models.CharField(max_length=1000)),
                ('popularity', models.IntegerField()),
            ],
        ),
    ]
