# Generated by Django 5.0.6 on 2024-06-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
