# Generated by Django 5.0.6 on 2024-06-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
