# Generated by Django 5.0.6 on 2024-06-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='request',
            field=models.SmallIntegerField(default=0),
        ),
    ]
